name: Run Tests and Build

on:
  push: {}
  pull_request: {}

env:
  CI: true
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.19]
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Set GOPATH and PATH
        run: |
          echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install dependencies
        run: |
          make download-dependencies
      - name: Lint
        run: |
          make lint
      - name: Run gofmt
        run: |
          diff -u <(echo -n) <(gofmt -d -e .)
      - name: Run go vet
        run: |
          make go-vet
      - name: Build plugin
        run: |
          make build
      - name: Test
        run: |
          # Github now comes with kustomize already installed
          sudo rm $(command -v kustomize) || true
          make kustomize
          XDG_CONFIG_HOME=$HOME/.config make test
